
services:
  php:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./var:/var/www/html/var
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./templates:/var/www/html/templates
      - ./migrations:/var/www/html/migrations
      - ./vendor:/var/www/html/vendor

    networks:
      - symfony-network

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - symfony-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - symfony-network

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - symfony-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - symfony-network

volumes:
  mysql-data:

networks:
  symfony-network:
